### ISSUE TITLE
All amounts are rounded

### ISSUE THREAD

**Issue by rossdargan** [rienafairefr/pynYNAB#38]
All of the Transaction.amounts that I check are whole integers... Adding them all up using a sql query:
session.query(func.sum(Transaction.amount)).scalar()

gives a whole number, and checking many transactions results in the same thing.

**Comment by rienafairefr** [comment]
Yes indeed, the amounts are stored in the internal database as whole integers. [this custom type](https://github.com/rienafairefr/pynYNAB/blob/master/pynYNAB/schema/types.py#L26). I would have thought this query would scale the value and give you back a normal value (in dollars), apparently not. The simplest solution is to scale the value yourself, divide by 1000 and this gives you the good value :-)

**Comment by rossdargan** [comment]
Once it's been placed into that custom type I don't think there is much I can do - I've tried dividing it by 1000 but the loss of precision is just maintained. I might be missing something!

```
>>> ynab_client.budget.be_transactions[6].amount/1000
-0.014
>>> ynab_client.budget.be_transactions[6].amount
-14.0
```

**Comment by rienafairefr** [comment]
Normally it should be transparent, the amount field should contain the actual dollar values. What is the amount displayed in YNAB website for this transaction ?

**Comment by rossdargan** [comment]
£13.03 :)

**Comment by rienafairefr** [comment]
yeah, that's an unacceptable rounding ! I can confirm the error, just replicated! Why that hasnt been caught by anyone else is remarkably horrible

**Comment by rienafairefr** [comment]
I think that's a python incompatibility. Are you using python 2 ?

**Comment by rienafairefr** [comment]
can you try latest master 7af5f1d ? I added a float(x) to handle how python 2.x does divisions involving integers.

**Comment by rossdargan** [comment]
Yup, that solves it - cheers!
