### ISSUE TITLE
Missing dependancies from setup.py

### ISSUE THREAD

**Issue by scottrobertson** [rienafairefr/pynYNAB#39]
At a bare minimum, we are missing the following from the setup.py dependancies:

```
sqlalchemy
aenum
```

There may be more, just not found them yet.

**Comment by rienafairefr** [comment]
you're right, there are some stuff in requirements.txt that are not in setup.py !

**Comment by rienafairefr** [comment]
should be fixed in 103d0e3564b70da0c661e80a4ebfb6a8350f1f73

**Comment by scottrobertson** [comment]
Awesome, thanks :)
