### ISSUE TITLE
Recent broken build

### ISSUE THREAD

**Issue by rienafairefr** [rienafairefr/pynYNAB#41]
Continuous testing showed a regression a few days ago, a server_error (unknown problem, the server can't process the request) is returned, and I cant really pin it on something. 

I'm not sure this is causing pushes to fail (for now I've seen it only on entity deletions) silently or something else, did you see anything failing, maybe in fintech-to-nynab @scottrobertson et al. ?

I've Fiddler-ed the requests: what is transmitted when the web app does something versus what is transmitted when the library does something. The request_data that is passed in json is identical, the only thing I see are some headers that are different, especially X-YNAB-Client-Request-Id  

I'm not sure this is something that changed recently in the web app code. Investigating....

**Comment by scottrobertson** [comment]
One thing i have learned recently is that they are sharing the JS library with the mobile apps, and I know they are doing some huge changes to the mobile apps at the moment, so we could be seeing those changes being deployed.

I will take a closer look this week and see if I can spot the issue. Unsure if fintech-to-ynab is working at the moment, will test that too.

**Comment by rienafairefr** [comment]
That's a possibility. 
After some investigation, I see the problem only with entity deletions, this is really weird. I'm cloning the requests as much as possible, down to detailed headers and everything, and it's still not processed as should be. Additions, no problem. Deletions, no chance. Pulling my hair out :-)

fintech-to-ynab should be fine you're just adding transactions ^^

**Comment by rienafairefr** [comment]
I seem to have cornered it. I was comparing the requests' json content with json-diff.com, and it doesn't differentiate between `"0"` and `false`, while ynab server does, so I thought the requests where equal when they weren't. The culprit is the credit_amount_adjusted field that should be an amount, not a boolean. Javascript is cruel !

**Comment by scottrobertson** [comment]
Awesome work!
