### ISSUE TITLE
Docs ?

### ISSUE THREAD

**Issue by andreroggeri** [rienafairefr/pynYNAB#42]
Is it possible to add more documentation to the Wiki ?

```
client.sync()
client.budget.be_transactions.append(transaction1)
client.budget.be_transactions.append(transaction2)
client.budget.be_payees.append(payee)
client.budget.push(3)
```

The example above doesn't explains how to create the transaction or the payee.

**Comment by rienafairefr** [comment]
I've added a page with an explanation of schema.Entities and how to create one, with an example for payees. Cheers!
