### ISSUE TITLE
ofximport: parse file before establishing a connection

### ISSUE THREAD

**Issue by chbndrhnns** [rienafairefr/pynYNAB#48]
Connection to YNAB takes some time. If there is an error with the file to be imported (it's missing, for example), this is only printed after the connection has been established. We could give faster feedback if reading the file before creating a connection.

**Comment by rienafairefr** [comment]
True that. Syncing down data from YNAB takes MASSIVE amount of time (I'm trying to bring this down). 

This change should be quite easy, just creating the client at the end once we have the list of transactions to push.

**Comment by rienafairefr** [comment]
I've pushed some changes, checkout 67425734fb1d874b4d1c891e956206c157c837db, there's now a verify before creating the client/syncing
