### ISSUE TITLE
AttributeError: 'nYnabClient_' object has no attribute 'sesssion'

### ISSUE THREAD

**Issue by TheGeekAndI** [rienafairefr/pynYNAB#56]
Hi,

I have downloaded the latest version of the package with `pip install` and used the examples of usage to get a connection. 

Everything works fine including the `client.sync()` line. 

When I run the `session = client.sesssion` line I get an `AttributeError: 'nYnabClient_' object has no attribute 'sesssion'`

The code I am trying to run on python v3.6 is the following:

```
from pynYNAB.Client import nYnabClient
from pynYNAB.connection import nYnabConnection
from sqlalchemy.sql import func
from datetime import datetime

connection = nYnabConnection(email="myEmail", password="myPassword")
connection.init_session()
client = nYnabClient(nynabconnection=connection, budgetname="API_test")
client.sync()

session = client.sesssion #<-- this is where I get the AttributeError

# sum of the amounts for all transactions younger than 10 weeks
session.query(func.sum(Transaction.amount)).filter(Transaction.date > datetime.datetime.now() - datetime.timedelta(weeks=10)).scalar()
```

any suggestions why that might be or what I have to change in the code of the package?

**Comment by natanweinberger** [comment]
Looks like it's possibly just a typo, "sesssion" instead of "session"?
