### ISSUE TITLE
Can't create new client. Returning NoBudgetNameException

### ISSUE THREAD

**Issue by EngieWare** [rienafairefr/pynYNAB#67]
Hello,

Writing a basic script to scrape loan repayments with particular tags. When I create a client by copying the example:

```
from pynYNAB.Client import nYnabClient

client = nYnabClient(email="############", password="######", budgetname='TestBudget')
client.sync()
```

It returns:
`pynYNAB.exceptions.NoBudgetNameException: you should pass a budget_name`

I have checked login details and the budget name for correctness but cannot determine what is causing this exception.

**Comment by rienafairefr** [comment]
I renamed some parameters some time ago for consistency (all snake_case), so maybe if you use budget_name='TestBudget' instead it's going to work. I had put a transitional release which handled both budgetname  and budget_name but I'm pretty sure budgetname argument is fully deprecated now. I should probably show a better error message, sorry about that.

**Comment by EngieWare** [comment]
No worries, thanks for the prompt reply. I did dive into the source and checked the exception, I noticed the snake case change and tried it as budget_name and Budget_Name but still no luck.

**Comment by EngieWare** [comment]
Hello, read through a few of the old issues and follwed your advice provided in [a previous issue](https://github.com/rienafairefr/pynYNAB/issues/63). Can I suggest you update the documentation to reflect this change?
